version: '3.9'

services:
  backend:
    build: .
    container_name: url_shortener_backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    volumes:
      - ./app:/usr/src/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload

  db:
    image: postgres:16-alpine
    container_name: url_shortener_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    container_name: url_shortener_redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  pgdata:
